name: 'Code coverage'
description: 'Update or check your code coverage'
inputs:
  token:
    description: 'The github token'
    required: true
  coverage-file:
    description: 'The coverage summary at clover format'
    required: true
    default: 'coverage.xml'
  summary-file:
    description: 'The summary JSON file to be pushed on the coverage branch'
    required: true
    default: 'coverage-summary.json'
  action:
    description: 'Do we want to update the base coverage, or to check it has not been degraded?'
    required: true
    default: 'update'
runs:
  using: 'node12'
  main: 'dist/index.js'
